# Site settings
title: Ivana Vel&iacute;&scaron;kov&aacute;
email: ivanaveliskova@gmail.com
description: I am a Philadelphia based front end web developer at WebLinc. I like to dabble in lots of things related to web but I really like a solid mix of pleasant visuals and simplicity.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ivanaveliskova.com" # the base hostname & protocol for your site
twitter_username: ivanaveliskova
github_username:  ivanaveliskova
linkedin_username: ivanaveliskova
instagram_username: ivanaveliskova
gmail_username: ivanaveliskova
disqusid: ivanaveliskova

# Build settings
markdown: kramdown
permalink: /blog/:title

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      social: "true"
      comments: "true"